import React, { useState, useEffect } from "react";
import {
  Store,
  Grid,
  TrendingUp,
  Cpu,
  Layers,
  Award,
  Video,
  Play,
  Pause,
  Star,
  Plus,
  Compass,
  CheckCircle,
  AlertCircle,
  X,
  CreditCard,
  Key,
  Database,
  Search,
  ChevronRight,
  ShieldAlert,
  Sliders,
  DollarSign,
  Activity,
  FileText,
  CloudSun,
  User,
  Heart,
  Share2,
  Bookmark,
  Check,
  Plane,
  Eye
} from "lucide-react";
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  CartesianGrid,
  PieChart,
  Pie,
  Cell
} from "recharts";

// --- STRUCTURAL INTERFACES ---
export interface AppRatingReview {
  id: string;
  user: string;
  rating: number;
  comment: string;
  date: string;
}

export interface AgritechApp {
  id: string;
  name: string;
  tagline: string;
  developer: string;
  category: "AI & Analytics" | "IoT & Irrigation" | "Drone Software" | "ERP & ERP Integrations" | "Developer APIs";
  description: string;
  fullDetails: string;
  rating: number;
  reviewsCount: number;
  reviews: AppRatingReview[];
  downloads: number;
  monthlyCost: number;
  freeTrialDays: number;
  isInstalled: boolean;
  isTrialActive: boolean;
  trialDaysLeft: number;
  isFeatured: boolean;
  demoVideoTitle: string;
  demoSimulationType: "drone" | "iot" | "erp" | "analytics" | "api";
  apiConnectorEndpoint?: string;
  revenueGenerated: number;
  subscriberCount: number;
}

// --- PRE-SEEDED APP CATALOG ---
const INITIAL_APPS: AgritechApp[] = [
  {
    id: "app-drone-scan",
    name: "SkyGaze Drone Mapping Engine",
    tagline: "Autonomous flight path planner & multi-spectral index builder.",
    developer: "AeroCrop Solutions",
    category: "Drone Software",
    description: "Connects directly to DJI and PX4 drone controllers. Automates NDVI, NDRE, and RGB orthomosaic mapping of cotton and sugarcane plots.",
    fullDetails: "Inject raw telemetry data to generate high-resolution topographical models. Detect plant count gaps and localized waterlogging within hours instead of days. Fully integrated with our 'Land & Assets' layout for automated field boundary detection.",
    rating: 4.8,
    reviewsCount: 142,
    reviews: [
      { id: "rev-1", user: "Harpreet Singh", rating: 5, comment: "NDVI maps generated by SkyGaze are incredibly accurate. Saved 4 tons of pesticide!", date: "2026-06-20" },
      { id: "rev-2", user: "Eswar Reddy", rating: 4, comment: "Great PX4 flight planner. Had a minor connection issue, but the latest update fixed it.", date: "2026-06-25" }
    ],
    downloads: 1250,
    monthlyCost: 29,
    freeTrialDays: 7,
    isInstalled: true,
    isTrialActive: false,
    trialDaysLeft: 0,
    isFeatured: true,
    demoVideoTitle: "Live Drone NDVI Orthomosaic Simulator",
    demoSimulationType: "drone",
    apiConnectorEndpoint: "https://api.aerocrop.io/v1/telemetry",
    revenueGenerated: 36250,
    subscriberCount: 320
  },
  {
    id: "app-iot-flow",
    name: "AquaLink IoT Irrigation Orchestrator",
    tagline: "Soil moisture-adaptive micro-irrigation controller.",
    developer: "HydroLogic Labs",
    category: "IoT & Irrigation",
    description: "Bridges LoRaWAN, Zigbee, and NBIoT soil monitors to physical solonoid valves for precision auto-drip cycles.",
    fullDetails: "Reduces water wastage by up to 40% by calculating real-time evapotranspiration coefficients. Incorporates national weather bureau telemetry to preemptively delay irrigation before heavy rainstorms.",
    rating: 4.6,
    reviewsCount: 98,
    reviews: [
      { id: "rev-3", user: "Ramesh Kumar", rating: 5, comment: "Perfect micro-irrigation trigger. Set it and forget it. Excellent battery saving features.", date: "2026-06-18" }
    ],
    downloads: 850,
    monthlyCost: 15,
    freeTrialDays: 14,
    isInstalled: false,
    isTrialActive: false,
    trialDaysLeft: 14,
    isFeatured: false,
    demoVideoTitle: "Dynamic AquaLink Soil Moisture Valve Simulator",
    demoSimulationType: "iot",
    apiConnectorEndpoint: "https://api.aqualink.net/sensors/stream",
    revenueGenerated: 12750,
    subscriberCount: 195
  },
  {
    id: "app-erp-ledger",
    name: "AgriLedger ERP Integration Bridge",
    tagline: "Syncs physical farm inventory directly to corporate accounting.",
    developer: "FinAgri Technologies",
    category: "ERP & ERP Integrations",
    description: "A continuous ledger exporter bridging seed, pesticide, and fuel consumption inventories with SAP and Oracle financial suits.",
    fullDetails: "Eliminate double-entry and missing paper bills. AgriLedger captures scalehouse delivery receipts via OCR, logs transport diesel liters, and exports comprehensive spreadsheet reports directly to corporate financial teams.",
    rating: 4.2,
    reviewsCount: 45,
    reviews: [
      { id: "rev-4", user: "NCDEX Supervisor", rating: 4, comment: "Very useful for audit-trail compliance. Pushes clean JSON formatted csv sheets directly.", date: "2026-06-12" }
    ],
    downloads: 410,
    monthlyCost: 45,
    freeTrialDays: 30,
    isInstalled: false,
    isTrialActive: true,
    trialDaysLeft: 18,
    isFeatured: false,
    demoVideoTitle: "ERP Invoice OCR & Ledger Stream Simulator",
    demoSimulationType: "erp",
    apiConnectorEndpoint: "https://api.agriledger.corp/v2/journal",
    revenueGenerated: 18450,
    subscriberCount: 82
  },
  {
    id: "app-ai-yield",
    name: "Ceres Agronomic Yield Predictor Pro",
    tagline: "Multi-layered crop development and market-timing advisor.",
    developer: "DeepMind Agri Labs",
    category: "AI & Analytics",
    description: "Leverages deep neural networks to correlate satellite imagery, heat units (GDD), and historical weather for peak yield forecasts.",
    fullDetails: "Gives high-accuracy harvest date optimization schedules. Predicts potential fungal outbrakes 10 days before visible symptoms show, and calculates real-time cost-benefit scenarios for alternative pesticide spray timings.",
    rating: 4.9,
    reviewsCount: 210,
    reviews: [
      { id: "rev-5", user: "Cooperative Lead Manager", rating: 5, comment: "Unbelievable accuracy for wheat rust outbreak forecasting. Absolute must-have.", date: "2026-06-27" }
    ],
    downloads: 3200,
    monthlyCost: 39,
    freeTrialDays: 5,
    isInstalled: true,
    isTrialActive: false,
    trialDaysLeft: 0,
    isFeatured: true,
    demoVideoTitle: "Ceres Crop Disease Risk Heatmap Projection",
    demoSimulationType: "analytics",
    apiConnectorEndpoint: "https://api.ceres-ai.org/v1/predict",
    revenueGenerated: 124800,
    subscriberCount: 540
  },
  {
    id: "app-api-coop",
    name: "Coop-Connect API Developer SDK",
    tagline: "Build custom widgets using the cooperative’s decentralized database.",
    developer: "Decentralized Agri OpenSource",
    category: "Developer APIs",
    description: "OAuth secured endpoints providing clean JSON streams of local sensor arrays, weather models, and transaction history.",
    fullDetails: "Enables independent developers to build localized web tools or native mobile widgets. Access secure historical price logs, soil profile data-points, and aggregated anonymized logistics queues.",
    rating: 4.5,
    reviewsCount: 34,
    reviews: [
      { id: "rev-6", user: "Suresh (Dev)", rating: 5, comment: "Clean REST endpoints. CORS headers are configured nicely. Sandbox mode is wonderful.", date: "2026-06-22" }
    ],
    downloads: 290,
    monthlyCost: 0,
    freeTrialDays: 0,
    isInstalled: false,
    isTrialActive: false,
    trialDaysLeft: 0,
    isFeatured: false,
    demoVideoTitle: "Live API Stream Sandbox JSON Terminal",
    demoSimulationType: "api",
    apiConnectorEndpoint: "https://api.cooperativehub.org/v1/sandbox",
    revenueGenerated: 0,
    subscriberCount: 110
  }
];

// --- ANALYTICS MOCK DATA ---
const POPULARITY_DATA = [
  { name: "Ceres AI", installs: 3200, revenue: 124800, score: 98 },
  { name: "SkyGaze Drone", installs: 1250, revenue: 36250, score: 85 },
  { name: "AquaLink IoT", installs: 850, revenue: 12750, score: 72 },
  { name: "AgriLedger", installs: 410, revenue: 18450, score: 64 },
  { name: "Coop-Connect", installs: 290, revenue: 0, score: 90 }
];

const REVENUE_SHARE_DATA = [
  { name: "Developer Payout (80%)", value: 153800 },
  { name: "Coop Reinvestment (20%)", value: 38450 }
];

const COLORS = ["#10b981", "#3b82f6", "#f59e0b", "#ef4444", "#8b5cf6"];

export default function AgritechMarketplace() {
  const [apps, setApps] = useState<AgritechApp[]>(INITIAL_APPS);
  const [selectedCategory, setSelectedCategory] = useState<string>("All");
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [activeAppDetails, setActiveAppDetails] = useState<AgritechApp | null>(null);
  
  // --- SUB-VIEW TOGGLE ---
  const [viewMode, setViewMode] = useState<"store" | "analytics" | "developer">("store");

  // --- INTERACTIVE DEMO PLAYER STATES ---
  const [activeDemoApp, setActiveDemoApp] = useState<AgritechApp>(INITIAL_APPS[0]);
  const [isPlayingDemo, setIsPlayingDemo] = useState<boolean>(false);
  const [demoProgress, setDemoProgress] = useState<number>(0);
  const [simulatedLog, setSimulatedLog] = useState<string[]>(["[System] Click Play to boot simulator pipeline..."]);

  // --- DEVELOPER PORTAL STATES ---
  const [devSplitRatio, setDevSplitRatio] = useState<number>(80); // 80% default
  const [newAppName, setNewAppName] = useState<string>("");
  const [newAppTagline, setNewAppTagline] = useState<string>("");
  const [newAppCategory, setNewAppCategory] = useState<"AI & Analytics" | "IoT & Irrigation" | "Drone Software" | "ERP & ERP Integrations" | "Developer APIs">("AI & Analytics");
  const [newAppPrice, setNewAppPrice] = useState<number>(19);
  const [newAppDesc, setNewAppDesc] = useState<string>("");
  const [developerKeys, setDeveloperKeys] = useState<{ clientID: string; clientSecret: string } | null>(null);

  // --- REVIEW SUBMISSION STATES ---
  const [reviewName, setReviewName] = useState<string>("");
  const [reviewRating, setReviewRating] = useState<number>(5);
  const [reviewComment, setReviewComment] = useState<string>("");

  // --- USER IN-APP WALLET BALANCE ---
  const [coopWalletCoins, setCoopWalletCoins] = useState<number>(4500);

  // --- SIMULATION STEP TIMER FOR THE INTERACTIVE DEMO VIDEOS ---
  useEffect(() => {
    let interval: NodeJS.Timeout | null = null;
    if (isPlayingDemo) {
      interval = setInterval(() => {
        setDemoProgress(prev => {
          if (prev >= 100) {
            setIsPlayingDemo(false);
            setSimulatedLog(logs => [...logs, "[Success] Pipeline processing cycle completed successfully! 100% data integrity verified."]);
            return 100;
          }
          const nextProg = prev + 5;
          
          // Generate realistic live data logs depending on the simulation type
          if (nextProg === 25) {
            if (activeDemoApp.demoSimulationType === "drone") {
              setSimulatedLog(logs => [...logs, "[AeroFlight] Calibrating 4K Multispectral Lens. Locked GPS altitude: 120m..."]);
            } else if (activeDemoApp.demoSimulationType === "iot") {
              setSimulatedLog(logs => [...logs, "[AquaSens] Soil probe detected 18.4% moisture in Sector Alpha. Initiating threshold checks..."]);
            } else if (activeDemoApp.demoSimulationType === "erp") {
              setSimulatedLog(logs => [...logs, "[AgriLedger] Scaling weightbridge invoice detected. Extracting text data via deep OCR..."]);
            } else if (activeDemoApp.demoSimulationType === "analytics") {
              setSimulatedLog(logs => [...logs, "[Ceres-AI] Satellite NDVI layers loaded. Correlating GDD cumulative index..."]);
            } else {
              setSimulatedLog(logs => [...logs, "[Sandbox] Fetching REST secure endpoint: GET /api/v1/telemetry..."]);
            }
          } else if (nextProg === 50) {
            if (activeDemoApp.demoSimulationType === "drone") {
              setSimulatedLog(logs => [...logs, "[AeroFlight] Flying grid row #3. Capturing 12 orthophotos. Wind: 8.4 knots. Safe."]);
            } else if (activeDemoApp.demoSimulationType === "iot") {
              setSimulatedLog(logs => [...logs, "[AquaSens] Solenoid valve pulse triggered. Fluid velocity: 3.5 liters/sec."]);
            } else if (activeDemoApp.demoSimulationType === "erp") {
              setSimulatedLog(logs => [...logs, "[AgriLedger] Match confirmed! Item ID: HIGH_GRADE_UREA_100KG. Price: ₹24,500."]);
            } else if (activeDemoApp.demoSimulationType === "analytics") {
              setSimulatedLog(logs => [...logs, "[Ceres-AI] Fungal outbreak risk index set: 12% (Low Hazard). Next check: 24h."]);
            } else {
              setSimulatedLog(logs => [...logs, "[Sandbox] Status code: 200 OK. Responding with 1,248 bytes of telemetry JSON metadata."]);
            }
          } else if (nextProg === 75) {
            if (activeDemoApp.demoSimulationType === "drone") {
              setSimulatedLog(logs => [...logs, "[AeroFlight] Processing drone stitched matrix layout. Stitching 48 JPEG-RAW frames..."]);
            } else if (activeDemoApp.demoSimulationType === "iot") {
              setSimulatedLog(logs => [...logs, "[AquaSens] Evapotranspiration offset applied. Auto-shutoff scheduled in 12 mins."]);
            } else if (activeDemoApp.demoSimulationType === "erp") {
              setSimulatedLog(logs => [...logs, "[AgriLedger] Writing secure ledger row in SAP Financial ledger database..."]);
            } else if (activeDemoApp.demoSimulationType === "analytics") {
              setSimulatedLog(logs => [...logs, "[Ceres-AI] Visual heatmap projected. Perfect alignment with sector grids."]);
            } else {
              setSimulatedLog(logs => [...logs, "[Sandbox] Active webhook dispatched. Client callback response completed."]);
            }
          }

          return nextProg;
        });
      }, 400);
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isPlayingDemo, activeDemoApp]);

  // Restart demo simulator when app selection changes
  const handleSelectDemoApp = (app: AgritechApp) => {
    setActiveDemoApp(app);
    setIsPlayingDemo(false);
    setDemoProgress(0);
    setSimulatedLog([`[System] Switch to ${app.name} simulator context. Click Play.`]);
  };

  // Run/Pause handler
  const toggleDemoPlayback = () => {
    if (demoProgress >= 100) {
      setDemoProgress(0);
      setSimulatedLog(["[System] Re-running simulation flow pipeline..."]);
    }
    setIsPlayingDemo(!isPlayingDemo);
  };

  // --- CONFIGURE KEY GENERATOR ---
  const generateDevKeys = () => {
    const id = "coop_client_" + Math.random().toString(36).substring(2, 10);
    const secret = "sec_val_" + Math.random().toString(36).substring(2, 18) + Math.random().toString(36).substring(2, 10);
    setDeveloperKeys({ clientID: id, clientSecret: secret });
    alert("New Developer Client ID & API Access Secret Token generated successfully! Store it securely.");
  };

  // --- SUBSCRIBE / INSTALL / LAUNCH ADDON ---
  const handleAppInstall = (appId: string) => {
    const target = apps.find(a => a.id === appId);
    if (!target) return;

    if (target.isInstalled) {
      // Uninstall
      if (confirm(`Do you wish to disconnect ${target.name}? Your configuration details will be kept.`)) {
        setApps(prev => prev.map(a => a.id === appId ? { ...a, isInstalled: false, isTrialActive: false } : a));
        alert(`${target.name} plugin integration deactivated.`);
      }
    } else {
      // Install / Subscribe / Purchase
      if (target.monthlyCost > 0) {
        // Paid
        const confirmSub = confirm(`Confirm subscription to ${target.name} for $${target.monthlyCost}/month. Subscriptions will be auto-debited via your cooperative ledger.`);
        if (confirmSub) {
          setApps(prev => prev.map(a => a.id === appId ? { ...a, isInstalled: true } : a));
          setCoopWalletCoins(prev => prev - (target.monthlyCost * 10)); // simulated price in coin tokens
          alert(`Successfully subscribed! ${target.name} is now actively running in your dashboard.`);
        }
      } else {
        // Free
        setApps(prev => prev.map(a => a.id === appId ? { ...a, isInstalled: true } : a));
        alert(`${target.name} open-source plugin initialized.`);
      }
    }
  };

  // --- FREE TRIAL TOGGLE ---
  const handleActivateTrial = (appId: string) => {
    setApps(prev => prev.map(a => {
      if (a.id === appId) {
        return {
          ...a,
          isInstalled: true,
          isTrialActive: true,
          trialDaysLeft: a.freeTrialDays
        };
      }
      return a;
    }));
    alert("Free Trial successfully activated! You have full access for the duration.");
  };

  // --- NEW REVIEW SUBMISSION ---
  const handleSubmitReview = (e: React.FormEvent, appId: string) => {
    e.preventDefault();
    if (!reviewName.trim() || !reviewComment.trim()) {
      alert("Please fill in both your name and review remarks.");
      return;
    }

    const newReview: AppRatingReview = {
      id: "rev-user-" + Date.now(),
      user: reviewName,
      rating: reviewRating,
      comment: reviewComment,
      date: new Date().toISOString().split("T")[0]
    };

    setApps(prev => prev.map(a => {
      if (a.id === appId) {
        const updatedReviews = [newReview, ...a.reviews];
        const newAvg = Number((updatedReviews.reduce((sum, r) => sum + r.rating, 0) / updatedReviews.length).toFixed(1));
        return {
          ...a,
          reviews: updatedReviews,
          reviewsCount: updatedReviews.length,
          rating: newAvg
        };
      }
      return a;
    }));

    // Clear review inputs
    setReviewName("");
    setReviewRating(5);
    setReviewComment("");
    alert("Your review has been verified and posted on the Agritech App Store marketplace!");
  };

  // --- PUBLISH NEW APP BY DEVELOPER ---
  const handlePublishApp = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newAppName.trim() || !newAppTagline.trim() || !newAppDesc.trim()) {
      alert("Please fill in the plugin name, sub-tagline, and direct technical parameters description.");
      return;
    }

    const customId = "app-custom-" + Date.now();
    const publishedApp: AgritechApp = {
      id: customId,
      name: newAppName,
      tagline: newAppTagline,
      developer: "Self Published Developer",
      category: newAppCategory,
      description: newAppDesc,
      fullDetails: `${newAppDesc} Designed under open-source compliant guidelines. Live analytics streaming included.`,
      rating: 5.0,
      reviewsCount: 0,
      reviews: [],
      downloads: 1,
      monthlyCost: newAppPrice,
      freeTrialDays: 7,
      isInstalled: false,
      isTrialActive: false,
      trialDaysLeft: 0,
      isFeatured: false,
      demoVideoTitle: `Demo simulation for ${newAppName}`,
      demoSimulationType: "api",
      revenueGenerated: 0,
      subscriberCount: 0
    };

    setApps(prev => [publishedApp, ...prev]);
    // reset form fields
    setNewAppName("");
    setNewAppTagline("");
    setNewAppDesc("");
    setNewAppPrice(19);
    alert(`Congratulations! "${newAppName}" has been successfully published to the Agritech App Store and marked for review verification.`);
  };

  // --- FILTERED APPS REGISTRY ---
  const filteredApps = apps.filter(app => {
    const matchesCategory = selectedCategory === "All" || app.category === selectedCategory;
    const matchesSearch = app.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          app.tagline.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          app.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          app.developer.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const activeSubscribedCount = apps.filter(a => a.isInstalled).length;
  const totalMonthlyPremiumSpend = apps.reduce((total, a) => a.isInstalled && !a.isTrialActive ? total + a.monthlyCost : total, 0);

  return (
    <div id="agritech-marketplace" className="bg-white rounded-2xl border border-slate-150 p-6 shadow-xs space-y-6">
      
      {/* 1. Header & Title Banner */}
      <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4 border-b border-slate-100 pb-5">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-emerald-50 border border-emerald-150 text-emerald-700 rounded-lg">
              <Store className="h-5 w-5 text-emerald-600 animate-pulse" />
            </div>
            <h3 className="font-extrabold text-slate-800 text-lg flex items-center gap-2">
              🌾 AgriTech Developer App Store & Integration Hub
            </h3>
          </div>
          <p className="text-[11px] text-slate-400 font-bold tracking-wide uppercase">
            Deploy third-party drone plugins, IoT connectors, accounting bridges, and developer APIs to your physical farm layout
          </p>
        </div>

        {/* View mode switcher */}
        <div className="flex items-center bg-slate-50 border p-1 rounded-xl gap-1">
          <button
            onClick={() => setViewMode("store")}
            className={`px-3 py-1.5 text-xs font-black rounded-lg cursor-pointer transition-all flex items-center gap-1.5 ${
              viewMode === "store"
                ? "bg-white text-emerald-700 shadow-xs border"
                : "text-slate-500 hover:text-slate-800"
            }`}
          >
            <Grid className="h-3.5 w-3.5" />
            App Store Catalog
          </button>
          <button
            onClick={() => setViewMode("analytics")}
            className={`px-3 py-1.5 text-xs font-black rounded-lg cursor-pointer transition-all flex items-center gap-1.5 ${
              viewMode === "analytics"
                ? "bg-white text-emerald-700 shadow-xs border"
                : "text-slate-500 hover:text-slate-800"
            }`}
          >
            <TrendingUp className="h-3.5 w-3.5" />
            Platform Analytics
          </button>
          <button
            onClick={() => setViewMode("developer")}
            className={`px-3 py-1.5 text-xs font-black rounded-lg cursor-pointer transition-all flex items-center gap-1.5 ${
              viewMode === "developer"
                ? "bg-white text-emerald-700 shadow-xs border"
                : "text-slate-500 hover:text-slate-800"
            }`}
          >
            <Cpu className="h-3.5 w-3.5" />
            Developer API Portal
          </button>
        </div>
      </div>

      {/* 2. Platform Usage Overview Bar */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 bg-slate-50 p-4 border rounded-2xl">
        
        <div className="bg-white p-3 rounded-xl border flex flex-col justify-between">
          <span className="text-[9px] font-black text-slate-400 uppercase tracking-wider">Subscribed Integrations</span>
          <div className="mt-1 flex items-baseline gap-1">
            <span className="text-xl font-extrabold text-slate-800">{activeSubscribedCount}</span>
            <span className="text-xs text-slate-400 font-bold">Active Modules</span>
          </div>
          <span className="text-[9px] text-emerald-600 font-bold block mt-1">✓ Pushing real-time telemetry</span>
        </div>

        <div className="bg-white p-3 rounded-xl border flex flex-col justify-between">
          <span className="text-[9px] font-black text-slate-400 uppercase tracking-wider">Monthly SaaS Spend</span>
          <div className="mt-1 flex items-baseline gap-1">
            <span className="text-xl font-extrabold text-slate-800">${totalMonthlyPremiumSpend}</span>
            <span className="text-xs text-slate-400 font-bold">/ Month</span>
          </div>
          <span className="text-[9px] text-slate-500 font-bold block mt-1">Deducted from crop exchange margins</span>
        </div>

        <div className="bg-white p-3 rounded-xl border flex flex-col justify-between">
          <span className="text-[9px] font-black text-slate-400 uppercase tracking-wider">Sandbox API Token Calls</span>
          <div className="mt-1 flex items-baseline gap-1">
            <span className="text-xl font-extrabold text-slate-800">4,281</span>
            <span className="text-xs text-slate-400 font-bold">Requests / 24h</span>
          </div>
          <span className="text-[9px] text-blue-600 font-bold block mt-1">99.98% successful responses</span>
        </div>

        <div className="bg-white p-3 rounded-xl border flex flex-col justify-between">
          <span className="text-[9px] font-black text-slate-400 uppercase tracking-wider">Demo In-App Wallet Balance</span>
          <div className="mt-1 flex items-baseline gap-1">
            <span className="text-xl font-extrabold text-slate-800">🪙 {coopWalletCoins}</span>
            <span className="text-xs text-slate-400 font-bold">Coins</span>
          </div>
          <span className="text-[9px] text-amber-600 font-bold block mt-1">
            <button onClick={() => setCoopWalletCoins(prev => prev + 1000)} className="underline cursor-pointer hover:text-amber-700">
              + Topup 1000 Coins (Simulated)
            </button>
          </span>
        </div>

      </div>

      {/* 3. DYNAMIC VIEWS */}

      {/* VIEW A: APP STORE CATALOG */}
      {viewMode === "store" && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          
          {/* Left Column: Apps Catalog (8 Columns) */}
          <div className="lg:col-span-8 space-y-6">
            
            {/* Search, Categories Filter Bar */}
            <div className="flex flex-col md:flex-row gap-3 items-center justify-between">
              
              {/* Category selector */}
              <div className="flex flex-wrap gap-1.5 w-full md:w-auto">
                {["All", "AI & Analytics", "IoT & Irrigation", "Drone Software", "ERP & ERP Integrations", "Developer APIs"].map(cat => (
                  <button
                    key={cat}
                    onClick={() => setSelectedCategory(cat)}
                    className={`px-3 py-1 rounded-lg text-xs font-black transition-colors cursor-pointer ${
                      selectedCategory === cat
                        ? "bg-slate-800 text-white"
                        : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                    }`}
                  >
                    {cat === "All" ? "📦 All Categories" : cat}
                  </button>
                ))}
              </div>

              {/* Search input */}
              <div className="relative w-full md:w-64">
                <Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="Search app store..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full bg-slate-50 border text-xs font-medium text-slate-700 pl-9 pr-3 py-2 rounded-xl focus:outline-none focus:ring-1 focus:ring-emerald-500"
                />
              </div>

            </div>

            {/* Featured App Showcase Banner */}
            {selectedCategory === "All" && searchQuery === "" && (
              <div className="p-5 bg-gradient-to-r from-emerald-950 to-slate-900 text-white rounded-2xl relative overflow-hidden border border-emerald-900 shadow-md">
                <div className="absolute right-3 top-3 bg-emerald-600 text-white text-[8px] font-black px-2 py-0.5 rounded uppercase tracking-wider animate-pulse">
                  Featured Plugin
                </div>

                <div className="space-y-2 relative z-10 max-w-lg">
                  <span className="text-[9px] font-extrabold text-emerald-400 uppercase tracking-wider block">Cooperative Verified Partnership</span>
                  <h4 className="text-base font-black text-slate-100">Ceres Agronomic Yield Predictor Pro</h4>
                  <p className="text-xs text-slate-300 leading-relaxed font-semibold">
                    Unleash artificial neural network analytics. Maps micro-climate sensor patterns to alert you on possible wheat rust outbreaks 10 days in advance.
                  </p>
                  <div className="flex items-center gap-3 pt-2 text-[11px] font-bold text-slate-300">
                    <span className="flex items-center gap-0.5 text-yellow-400"><Star className="h-3.5 w-3.5 fill-current" /> 4.9</span>
                    <span>• 3,200+ active installs</span>
                    <span>• 5-Day Free Trial available</span>
                  </div>
                  
                  <div className="flex gap-2 pt-2">
                    <button
                      onClick={() => handleAppInstall("app-ai-yield")}
                      className={`px-4 py-2 text-xs font-black rounded-lg cursor-pointer transition-colors ${
                        apps.find(a => a.id === "app-ai-yield")?.isInstalled
                          ? "bg-rose-600 hover:bg-rose-700 text-white"
                          : "bg-emerald-500 hover:bg-emerald-600 text-white"
                      }`}
                    >
                      {apps.find(a => a.id === "app-ai-yield")?.isInstalled ? "Deactivate Ceres" : "Subscribe ($39/mo)"}
                    </button>
                    <button
                      onClick={() => {
                        const app = apps.find(a => a.id === "app-ai-yield");
                        if (app) handleSelectDemoApp(app);
                      }}
                      className="px-3 py-2 bg-slate-800 hover:bg-slate-750 text-slate-200 text-xs font-black rounded-lg cursor-pointer flex items-center gap-1"
                    >
                      <Play className="h-3 w-3 fill-current" /> Play Live Demo
                    </button>
                  </div>
                </div>

                {/* Aesthetic ambient gradient ball */}
                <div className="absolute -right-16 -bottom-16 w-48 h-48 bg-emerald-600/20 rounded-full blur-2xl" />
              </div>
            )}

            {/* Apps Cards List */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {filteredApps.map(app => (
                <div key={app.id} className="p-5 bg-white border rounded-2xl hover:shadow-md transition-shadow flex flex-col justify-between space-y-4">
                  
                  <div className="space-y-2">
                    {/* Badge and Title */}
                    <div className="flex justify-between items-start">
                      <span className="text-[8px] font-black uppercase px-2 py-0.5 rounded bg-slate-100 border text-slate-500">
                        {app.category}
                      </span>
                      <span className="text-[10px] text-slate-400 font-extrabold font-mono">
                        by {app.developer}
                      </span>
                    </div>

                    <h4 className="text-sm font-extrabold text-slate-800 leading-tight">
                      {app.name}
                    </h4>
                    <p className="text-[11px] font-semibold text-slate-400 italic">
                      {app.tagline}
                    </p>
                    <p className="text-xs text-slate-600 leading-relaxed font-medium">
                      {app.description}
                    </p>
                  </div>

                  <div className="space-y-3 pt-3 border-t border-slate-100">
                    
                    {/* App Rating, Reviews and pricing info */}
                    <div className="flex justify-between items-center text-[11px] font-bold">
                      <div className="flex items-center gap-1 text-slate-600">
                        <span className="flex items-center text-yellow-400">
                          <Star className="h-3.5 w-3.5 fill-current" />
                        </span>
                        <span>{app.rating}</span>
                        <span className="text-slate-400 font-medium">({app.reviewsCount} reviews)</span>
                      </div>
                      <div className="text-slate-700 font-mono">
                        {app.monthlyCost > 0 ? `$${app.monthlyCost}/month` : "Free OpenSource"}
                      </div>
                    </div>

                    {/* Subscription Action & Trials */}
                    <div className="flex flex-wrap gap-2 pt-1">
                      
                      {/* Subscription Toggle */}
                      <button
                        onClick={() => handleAppInstall(app.id)}
                        className={`flex-1 min-w-[100px] py-1.5 rounded-lg text-xs font-black cursor-pointer text-center transition-all ${
                          app.isInstalled
                            ? "bg-rose-50 text-rose-700 border border-rose-200 hover:bg-rose-100"
                            : "bg-slate-900 hover:bg-slate-800 text-white"
                        }`}
                      >
                        {app.isInstalled ? "Disconnect" : app.monthlyCost > 0 ? "Subscribe" : "Deploy"}
                      </button>

                      {/* Free Trial Button if not active/installed */}
                      {!app.isInstalled && app.freeTrialDays > 0 && (
                        <button
                          onClick={() => handleActivateTrial(app.id)}
                          className="px-2.5 py-1.5 border border-dashed border-emerald-500 bg-emerald-50/50 hover:bg-emerald-50 text-emerald-700 text-xs font-black rounded-lg cursor-pointer"
                        >
                          {app.freeTrialDays}-Day Free Trial
                        </button>
                      )}

                      {/* Open Details Panel */}
                      <button
                        onClick={() => {
                          setActiveAppDetails(app);
                          handleSelectDemoApp(app);
                        }}
                        className="p-1.5 bg-slate-100 hover:bg-slate-200 rounded-lg cursor-pointer"
                        title="View reviews & live API config"
                      >
                        <ChevronRight className="h-4 w-4 text-slate-500" />
                      </button>

                    </div>

                    {/* Active Status Display */}
                    {app.isInstalled && (
                      <div className="flex items-center justify-between text-[10px] font-bold bg-emerald-50 border border-emerald-100 p-2 rounded-lg">
                        <span className="flex items-center gap-1 text-emerald-800">
                          <CheckCircle className="h-3.5 w-3.5 text-emerald-600" />
                          {app.isTrialActive ? `Active Free Trial` : "System Plugin Connected"}
                        </span>
                        {app.isTrialActive && (
                          <span className="text-emerald-700 font-mono font-black">
                            {app.trialDaysLeft} Days Remaining
                          </span>
                        )}
                        {!app.isTrialActive && app.apiConnectorEndpoint && (
                          <span className="text-slate-400 font-mono text-[9px] truncate max-w-[120px]" title={app.apiConnectorEndpoint}>
                            Endpoint: {app.apiConnectorEndpoint.replace("https://", "")}
                          </span>
                        )}
                      </div>
                    )}

                  </div>

                </div>
              ))}
            </div>

          </div>

          {/* Right Column: Interactive App Demo & Trials Sidebar (4 Columns) */}
          <div className="lg:col-span-4 space-y-6">
            
            {/* 1. Interactive Demo Simulator Player */}
            <div className="p-5 bg-slate-950 text-white rounded-2xl border border-slate-800 space-y-4">
              <div className="flex justify-between items-center pb-2 border-b border-slate-900">
                <div className="flex items-center gap-1.5">
                  <Video className="h-4 w-4 text-emerald-400" />
                  <h4 className="text-[10px] font-black uppercase tracking-wider text-slate-300">
                    Interactive App Demo Player
                  </h4>
                </div>
                <span className="text-[8px] font-black bg-rose-950 text-rose-400 px-1.5 py-0.5 rounded border border-rose-900 uppercase">
                  Live Sim
                </span>
              </div>

              {/* Demo Selection Switcher */}
              <div>
                <label className="text-[9px] font-black text-slate-400 uppercase block mb-1">Select App Demo:</label>
                <select
                  value={activeDemoApp.id}
                  onChange={(e) => {
                    const found = apps.find(a => a.id === e.target.value);
                    if (found) handleSelectDemoApp(found);
                  }}
                  className="w-full bg-slate-900 border border-slate-800 text-xs font-extrabold text-slate-300 px-3 py-2 rounded-xl focus:outline-none focus:ring-1 focus:ring-emerald-500"
                >
                  {apps.map(a => (
                    <option key={a.id} value={a.id}>{a.name}</option>
                  ))}
                </select>
              </div>

              {/* Screen Mockup Area */}
              <div className="bg-slate-900 aspect-video rounded-xl border border-slate-800 relative overflow-hidden flex flex-col justify-between p-3 font-mono">
                
                {/* Simulated Visual Output Depending on Simulation Type */}
                <div className="space-y-1 relative z-10 text-[10px]">
                  <div className="flex justify-between items-center text-[9px] text-slate-500 border-b border-slate-800/60 pb-1">
                    <span>{activeDemoApp.demoVideoTitle}</span>
                    <span className="text-emerald-400 animate-pulse font-black">● SIMULATOR ACTIVE</span>
                  </div>

                  {/* Render Visual Graphics Mockups */}
                  {activeDemoApp.demoSimulationType === "drone" && (
                    <div className="pt-2 text-center space-y-2">
                      <div className="flex justify-center gap-2 items-center text-xs">
                        <Plane className="h-5 w-5 text-indigo-400 animate-bounce" />
                        <span className="text-slate-300 font-bold">Drone Flight Grid Row 3/8</span>
                      </div>
                      <div className="grid grid-cols-4 gap-1 max-w-[150px] mx-auto text-[8px]">
                        <span className="p-1 bg-emerald-950 border border-emerald-900 text-emerald-400 rounded">NDVI: 0.8</span>
                        <span className="p-1 bg-emerald-950 border border-emerald-900 text-emerald-400 rounded">NDVI: 0.72</span>
                        <span className="p-1 bg-rose-950 border border-rose-900 text-rose-400 rounded">NDVI: 0.2</span>
                        <span className="p-1 bg-emerald-950 border border-emerald-900 text-emerald-400 rounded">NDVI: 0.81</span>
                      </div>
                    </div>
                  )}

                  {activeDemoApp.demoSimulationType === "iot" && (
                    <div className="pt-2 text-center space-y-2">
                      <div className="flex justify-center gap-2 items-center text-xs">
                        <Activity className="h-5 w-5 text-sky-400 animate-spin" />
                        <span className="text-slate-300 font-bold">Solenoid Valve Pulsing</span>
                      </div>
                      <div className="text-[11px] text-sky-300 font-black">
                        Flow Rate: 4.2 L/s • Soil Moisture: 19.8%
                      </div>
                    </div>
                  )}

                  {activeDemoApp.demoSimulationType === "erp" && (
                    <div className="pt-2 text-center space-y-2">
                      <div className="flex justify-center gap-2 items-center text-xs">
                        <FileText className="h-5 w-5 text-amber-400" />
                        <span className="text-slate-300 font-bold">OCR Invoice Reader</span>
                      </div>
                      <div className="text-[8.5px] bg-slate-950 p-1 border border-slate-800 text-left text-amber-500 rounded max-w-[180px] mx-auto truncate">
                        EXTRACTED: ID: NITROGEN_BAG_50KG | INR: 24,500
                      </div>
                    </div>
                  )}

                  {activeDemoApp.demoSimulationType === "analytics" && (
                    <div className="pt-2 text-center space-y-2">
                      <div className="flex justify-center gap-2 items-center text-xs">
                        <TrendingUp className="h-5 w-5 text-emerald-400" />
                        <span className="text-slate-300 font-bold">Crop Health Yield Predictor</span>
                      </div>
                      <div className="text-[10px] text-emerald-400 font-black">
                        Pred. Yield: 4.8 tons/acre (Optimal GDD reached)
                      </div>
                    </div>
                  )}

                  {activeDemoApp.demoSimulationType === "api" && (
                    <div className="pt-1 space-y-1">
                      <span className="text-[8.5px] text-slate-500 block">Response JSON Payload Stream:</span>
                      <div className="text-[7.5px] bg-slate-950 p-1 border border-slate-800 text-slate-300 rounded overflow-x-auto">
                        {"{"} "sensorId": "node-4082", "temp_c": 31.4, "status": "active" {"}"}
                      </div>
                    </div>
                  )}

                </div>

                {/* Progress bar overlay */}
                <div className="space-y-1">
                  <div className="flex justify-between items-center text-[8px] text-slate-500">
                    <span>Simulation Progress</span>
                    <span>{demoProgress}%</span>
                  </div>
                  <div className="w-full h-1 bg-slate-850 rounded-full overflow-hidden">
                    <div className="h-full bg-emerald-500 transition-all duration-300" style={{ width: `${demoProgress}%` }} />
                  </div>
                </div>

                {/* Ambient glow */}
                <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 to-transparent pointer-events-none" />
              </div>

              {/* Demo Player Controls */}
              <div className="flex gap-2">
                <button
                  onClick={toggleDemoPlayback}
                  className="flex-1 py-2 bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-black rounded-lg text-xs cursor-pointer flex items-center justify-center gap-1.5"
                >
                  {isPlayingDemo ? (
                    <>
                      <Pause className="h-3.5 w-3.5 fill-current" /> Pause Demo
                    </>
                  ) : (
                    <>
                      <Play className="h-3.5 w-3.5 fill-current" /> Play Live Simulation
                    </>
                  )}
                </button>
                <button
                  onClick={() => {
                    setDemoProgress(0);
                    setIsPlayingDemo(false);
                    setSimulatedLog([`[System] Reset simulator for ${activeDemoApp.name}.`]);
                  }}
                  className="px-3 bg-slate-800 hover:bg-slate-750 text-slate-300 text-xs font-black rounded-lg cursor-pointer"
                  title="Reset Simulator"
                >
                  Reset
                </button>
              </div>

              {/* Console Logs */}
              <div className="space-y-1.5">
                <span className="text-[9px] font-black text-slate-400 uppercase tracking-wider block">Simulator Console Logs:</span>
                <div className="bg-slate-950 p-3 rounded-lg border border-slate-900 font-mono text-[9px] text-slate-400 space-y-1 max-h-[85px] overflow-y-auto">
                  {simulatedLog.map((log, i) => (
                    <div key={i} className="leading-tight">
                      <span className="text-slate-600 font-bold">[{i + 1}]</span> {log}
                    </div>
                  ))}
                </div>
              </div>

            </div>

            {/* 2. active subscriptions & trial management card */}
            <div className="p-5 bg-slate-50 border rounded-2xl space-y-4">
              <div className="flex items-center gap-1.5 pb-2 border-b">
                <Bookmark className="h-4.5 w-4.5 text-slate-700" />
                <h4 className="text-xs font-black uppercase text-slate-800 tracking-wider">
                  Subscription & Trial Manager
                </h4>
              </div>

              <div className="space-y-3">
                {apps.filter(a => a.isInstalled).length === 0 ? (
                  <p className="text-xs text-slate-400 font-semibold italic text-center py-4">
                    No active software integrations deployed. Navigate app store to connect third-party platforms.
                  </p>
                ) : (
                  <div className="space-y-2">
                    {apps.filter(a => a.isInstalled).map(app => (
                      <div key={app.id} className="p-3 bg-white border rounded-xl flex items-center justify-between gap-2">
                        <div className="truncate">
                          <h5 className="text-xs font-black text-slate-800 truncate">{app.name}</h5>
                          <span className="text-[9px] font-extrabold text-slate-400 block uppercase font-mono">
                            {app.isTrialActive ? `⏳ Trial: ${app.trialDaysLeft} Days Left` : `✓ Active Plan: $${app.monthlyCost}/mo`}
                          </span>
                        </div>
                        <button
                          onClick={() => handleAppInstall(app.id)}
                          className="px-2 py-1 text-[9px] font-black text-rose-600 hover:text-white hover:bg-rose-600 border border-rose-200 rounded-md cursor-pointer transition-colors"
                        >
                          Disconnect
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>

          </div>

        </div>
      )}

      {/* VIEW B: USAGE ANALYTICS DASHBOARD */}
      {viewMode === "analytics" && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          
          {/* Main analytic charts (8 columns) */}
          <div className="lg:col-span-8 bg-white border p-5 rounded-2xl space-y-6">
            
            <div className="space-y-1 pb-3 border-b">
              <h4 className="text-xs font-black text-slate-800 uppercase tracking-wider">
                Third-Party Integration Popularity & SaaS Downloads
              </h4>
              <p className="text-[11px] text-slate-400 font-semibold">
                Quantifying total developer installs, active platform queries, and aggregate performance scores.
              </p>
            </div>

            {/* Recharts Bar Chart */}
            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={POPULARITY_DATA}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} />
                  <XAxis dataKey="name" tick={{ fontSize: 10, fontWeight: "bold" }} />
                  <YAxis tick={{ fontSize: 10, fontWeight: "bold" }} />
                  <Tooltip contentStyle={{ fontSize: 11, fontWeight: "bold" }} />
                  <Legend wrapperStyle={{ fontSize: 10, fontWeight: "bold" }} />
                  <Bar dataKey="installs" fill="#10b981" name="Aggregate App Downloads" radius={[4, 4, 0, 0]} />
                  <Bar dataKey="score" fill="#3b82f6" name="Reliability Performance (Score /100)" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>

            <div className="p-4 bg-slate-50 border rounded-xl flex items-center gap-3">
              <Sliders className="h-5 w-5 text-emerald-600" />
              <div className="space-y-0.5">
                <span className="text-[10px] font-black text-slate-700 uppercase block">Developer Revenue Sharing Agreement</span>
                <p className="text-[11.5px] leading-relaxed text-slate-500 font-semibold">
                  By default, 80% of monthly subscription fees pass directly to the developer, while 20% is reinvested into the community IoT LoRaWAN antenna array. Use the Developer Portal tab to adjust mock revenue sharing logic.
                </p>
              </div>
            </div>

          </div>

          {/* Revenue distribution breakdown (4 columns) */}
          <div className="lg:col-span-4 bg-white border p-5 rounded-2xl space-y-6">
            
            <div className="space-y-1 pb-3 border-b">
              <h4 className="text-xs font-black text-slate-800 uppercase tracking-wider">
                Total Revenue Distribution
              </h4>
              <span className="text-[10px] text-emerald-600 font-bold block">Annual Aggregate Pool</span>
            </div>

            {/* Recharts Pie Chart */}
            <div className="h-56 flex flex-col justify-center items-center">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={REVENUE_SHARE_DATA}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={75}
                    paddingAngle={4}
                    dataKey="value"
                  >
                    {REVENUE_SHARE_DATA.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(value) => `$${value}`} contentStyle={{ fontSize: 10, fontWeight: "black" }} />
                </PieChart>
              </ResponsiveContainer>

              <div className="flex gap-4 text-[10px] font-extrabold text-slate-600">
                <span className="flex items-center gap-1"><span className="w-2.5 h-2.5 bg-emerald-500 rounded-full" /> Developer: $153.8k</span>
                <span className="flex items-center gap-1"><span className="w-2.5 h-2.5 bg-blue-500 rounded-full" /> Coop Fund: $38.4k</span>
              </div>
            </div>

            <div className="bg-emerald-50/60 p-4 rounded-xl border border-emerald-100 text-[11px] font-semibold text-emerald-900 leading-relaxed space-y-1">
              <span className="font-extrabold text-emerald-800 uppercase block">Platform Health Check:</span>
              <p>✓ All drone flight plugins are fully responsive.</p>
              <p>✓ 14,210 megabytes of multi-spectral imagery compressed.</p>
              <p>✓ LoRaWAN packet latency: 12ms (Excellent).</p>
            </div>

          </div>

        </div>
      )}

      {/* VIEW C: DEVELOPER API PORTAL & PUBLISHER HUB */}
      {viewMode === "developer" && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          
          {/* Publisher Hub - Create new integration (7 columns) */}
          <div className="lg:col-span-7 bg-white border p-5 rounded-2xl space-y-5">
            
            <div className="space-y-1 pb-3 border-b">
              <h4 className="text-xs font-black text-slate-800 uppercase tracking-wider">
                🔨 Self-Publish Third-Party Agritech Plugin
              </h4>
              <p className="text-[11.5px] text-slate-400 font-semibold">
                Are you an Agritech startup or developer? Fill out this sandbox form to publish your SaaS plugin directly into the cooperative store.
              </p>
            </div>

            <form onSubmit={handlePublishApp} className="space-y-4 text-xs">
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="text-[10px] font-black text-slate-500 uppercase block mb-1">Plugin Name:</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. HydroScale Intelligent Well"
                    value={newAppName}
                    onChange={(e) => setNewAppName(e.target.value)}
                    className="w-full bg-slate-50 border font-bold text-slate-700 px-3 py-2 rounded-xl focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  />
                </div>
                <div>
                  <label className="text-[10px] font-black text-slate-500 uppercase block mb-1">Catchy Sub-Tagline:</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Automated ground-water calculation."
                    value={newAppTagline}
                    onChange={(e) => setNewAppTagline(e.target.value)}
                    className="w-full bg-slate-50 border font-bold text-slate-700 px-3 py-2 rounded-xl focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="text-[10px] font-black text-slate-500 uppercase block mb-1">Plugin Category:</label>
                  <select
                    value={newAppCategory}
                    onChange={(e) => setNewAppCategory(e.target.value as any)}
                    className="w-full bg-slate-50 border font-bold text-slate-700 px-3 py-2 rounded-xl focus:outline-none focus:ring-1 focus:ring-emerald-500 cursor-pointer"
                  >
                    <option value="AI & Analytics">AI & Analytics</option>
                    <option value="IoT & Irrigation">IoT & Irrigation</option>
                    <option value="Drone Software">Drone Software</option>
                    <option value="ERP & ERP Integrations">ERP & ERP Integrations</option>
                    <option value="Developer APIs">Developer APIs</option>
                  </select>
                </div>
                <div>
                  <label className="text-[10px] font-black text-slate-500 uppercase block mb-1">Monthly Cost ($):</label>
                  <input
                    type="number"
                    min={0}
                    value={newAppPrice}
                    onChange={(e) => setNewAppPrice(Number(e.target.value))}
                    className="w-full bg-slate-50 border font-bold text-slate-700 px-3 py-2 rounded-xl focus:outline-none focus:ring-1 focus:ring-emerald-500 font-mono"
                  />
                </div>
              </div>

              <div>
                <label className="text-[10px] font-black text-slate-500 uppercase block mb-1">Direct Technical Parameters & App Details:</label>
                <textarea
                  rows={3}
                  required
                  placeholder="Describe in detail how your software leverages drone flight logs, connects to sensor arrays, or exports standard JSON csv logs to the Agri ERP bridge."
                  value={newAppDesc}
                  onChange={(e) => setNewAppDesc(e.target.value)}
                  className="w-full bg-slate-50 border font-semibold text-slate-700 px-3 py-2 rounded-xl focus:outline-none focus:ring-1 focus:ring-emerald-500"
                />
              </div>

              <button
                type="submit"
                className="w-full py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-black rounded-xl text-xs cursor-pointer transition-colors"
              >
                Publish Plugin & Set Webhooks Live
              </button>

            </form>

          </div>

          {/* Developers API keys generator and revenue sliders (5 columns) */}
          <div className="lg:col-span-5 space-y-6">
            
            {/* API access tokens generator */}
            <div className="p-5 bg-slate-900 text-white rounded-2xl border border-slate-800 space-y-4">
              <div className="flex items-center gap-1.5 pb-2 border-b border-slate-800">
                <Key className="h-4.5 w-4.5 text-emerald-400" />
                <h4 className="text-[10px] font-black uppercase tracking-wider text-slate-300">
                  Developer Platform API Credentials
                </h4>
              </div>

              <p className="text-[10.5px] text-slate-400 font-semibold leading-relaxed">
                Generate secure sandbox OAuth tokens to pull simulated local weather feeds, sensor telemetry logs, and digital twins directly to your custom widgets.
              </p>

              {developerKeys ? (
                <div className="space-y-3 font-mono text-[10px]">
                  <div className="bg-slate-950 p-2 border border-slate-800 rounded">
                    <span className="text-slate-500 block text-[8px] uppercase">OAuth Client ID:</span>
                    <span className="text-emerald-400 font-bold break-all">{developerKeys.clientID}</span>
                  </div>
                  <div className="bg-slate-950 p-2 border border-slate-800 rounded">
                    <span className="text-slate-500 block text-[8px] uppercase">OAuth Client Secret:</span>
                    <span className="text-amber-400 font-bold break-all">{developerKeys.clientSecret}</span>
                  </div>
                  <div className="flex gap-2 text-[9px]">
                    <button
                      onClick={() => {
                        navigator.clipboard.writeText(developerKeys.clientSecret);
                        alert("Client Secret copied to clipboard.");
                      }}
                      className="px-2.5 py-1 bg-slate-800 hover:bg-slate-750 text-slate-300 rounded cursor-pointer"
                    >
                      Copy Secret
                    </button>
                    <button
                      onClick={generateDevKeys}
                      className="px-2.5 py-1 bg-slate-800 hover:bg-slate-750 text-slate-300 rounded cursor-pointer"
                    >
                      Regenerate
                    </button>
                  </div>
                </div>
              ) : (
                <button
                  onClick={generateDevKeys}
                  className="w-full py-2 bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-black rounded-xl text-xs cursor-pointer transition-colors"
                >
                  Generate New API Access Credentials
                </button>
              )}

              <div className="p-3 bg-slate-950 border border-slate-850 rounded-xl text-[9.5px] font-mono text-slate-500 flex items-center gap-2">
                <Database className="h-4 w-4 text-emerald-600 shrink-0" />
                <span>Base Endpoint: https://api.cooperativehub.org/v1</span>
              </div>
            </div>

            {/* Simulated Revenue Sharing Calculator */}
            <div className="p-5 bg-slate-50 border rounded-2xl space-y-4">
              <div className="flex justify-between items-center pb-2 border-b">
                <span className="text-[10px] font-black text-slate-700 uppercase tracking-wider">
                  Interactive Revenue sharing slider
                </span>
                <span className="text-[9px] bg-emerald-100 text-emerald-800 px-1.5 py-0.5 rounded font-black font-mono">
                  LIVE MODEL
                </span>
              </div>

              <div className="space-y-3 text-xs">
                <div>
                  <div className="flex justify-between text-[11px] font-extrabold text-slate-600 mb-1">
                    <span>Developer Share:</span>
                    <span className="text-slate-800 font-mono font-black">{devSplitRatio}%</span>
                  </div>
                  <input
                    type="range"
                    min={50}
                    max={95}
                    value={devSplitRatio}
                    onChange={(e) => setDevSplitRatio(Number(e.target.value))}
                    className="w-full h-1 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-emerald-600"
                  />
                  <div className="flex justify-between text-[9px] text-slate-400 mt-1 font-bold">
                    <span>Min: 50%</span>
                    <span>Max: 95%</span>
                  </div>
                </div>

                <div className="p-3 bg-white border rounded-xl space-y-1.5 text-[11px] font-semibold">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Total Prototyped Subscribers:</span>
                    <span className="text-slate-800 font-bold font-mono">1,310</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Avg Subscription Ticket:</span>
                    <span className="text-slate-800 font-bold font-mono">$15 / mo</span>
                  </div>
                  <div className="flex justify-between border-t pt-1.5">
                    <span className="text-slate-600 font-extrabold">Your Est. Monthly Earnings:</span>
                    <span className="text-emerald-700 font-black font-mono text-xs">
                      ${Math.round(1310 * 15 * (devSplitRatio / 100)).toLocaleString()}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600 font-extrabold">Cooperative Reinvest Pool:</span>
                    <span className="text-blue-700 font-black font-mono text-xs">
                      ${Math.round(1310 * 15 * ((100 - devSplitRatio) / 100)).toLocaleString()}
                    </span>
                  </div>
                </div>
              </div>
            </div>

          </div>

        </div>
      )}

      {/* 4. MODAL DETAILED POPUP: REVIEWS, DEMOS & FULL APP SPECS */}
      {activeAppDetails && (
        <div className="fixed inset-0 bg-slate-900/60 flex justify-center items-center p-4 z-50 overflow-y-auto">
          
          <div className="bg-white rounded-2xl max-w-2xl w-full border border-slate-200 shadow-xl overflow-hidden flex flex-col max-h-[90vh]">
            
            {/* Header */}
            <div className="p-5 bg-slate-50 border-b flex justify-between items-start">
              <div>
                <span className="text-[9px] font-black uppercase text-slate-400 block tracking-wider mb-0.5">
                  {activeAppDetails.category} Integration Details
                </span>
                <h4 className="text-base font-extrabold text-slate-800">
                  {activeAppDetails.name}
                </h4>
              </div>
              <button
                onClick={() => setActiveAppDetails(null)}
                className="p-1.5 hover:bg-slate-200 rounded-lg cursor-pointer"
              >
                <X className="h-5 w-5 text-slate-500" />
              </button>
            </div>

            {/* Scrollable specs */}
            <div className="p-6 space-y-6 overflow-y-auto">
              
              <div className="space-y-2">
                <h5 className="text-[11px] font-black text-slate-400 uppercase tracking-wide">Detailed Specifications & Compatibility</h5>
                <p className="text-xs text-slate-600 leading-relaxed font-semibold">
                  {activeAppDetails.fullDetails}
                </p>
              </div>

              {/* Developer API Webhook Stream if present */}
              {activeAppDetails.apiConnectorEndpoint && (
                <div className="p-4 bg-slate-900 text-white rounded-xl space-y-2 font-mono text-xs">
                  <div className="flex justify-between items-center text-[10px] text-slate-400 pb-1.5 border-b border-slate-800">
                    <span className="font-bold flex items-center gap-1"><Database className="h-3.5 w-3.5 text-emerald-400" /> ACTIVE API ENDPOINT</span>
                    <span className="text-emerald-400 font-black">Status: Verified</span>
                  </div>
                  <div className="flex justify-between text-[11px]">
                    <span className="text-slate-500">Live Webhook Endpoint:</span>
                    <span className="text-slate-200 select-all font-bold">{activeAppDetails.apiConnectorEndpoint}</span>
                  </div>
                  <div className="flex justify-between text-[11px]">
                    <span className="text-slate-500">Data-Stream Transferred (This Month):</span>
                    <span className="text-emerald-400 font-bold">142.8 Megabytes</span>
                  </div>
                </div>
              )}

              {/* Reviews List */}
              <div className="space-y-4">
                <div className="flex justify-between items-center pb-2 border-b">
                  <h5 className="text-[11px] font-black text-slate-400 uppercase tracking-wide">
                    App Ratings & Reviews ({activeAppDetails.reviewsCount})
                  </h5>
                  <div className="flex items-center gap-0.5 text-xs font-bold text-slate-700">
                    <Star className="h-4 w-4 text-yellow-400 fill-current" />
                    <span>{activeAppDetails.rating} out of 5</span>
                  </div>
                </div>

                <div className="space-y-3">
                  {activeAppDetails.reviews.length === 0 ? (
                    <p className="text-xs text-slate-400 font-semibold italic">No community reviews posted yet. Be the first to share your feedback below.</p>
                  ) : (
                    activeAppDetails.reviews.map(rev => (
                      <div key={rev.id} className="p-3.5 bg-slate-50 rounded-xl space-y-1 text-xs">
                        <div className="flex justify-between items-center text-[11px] font-extrabold text-slate-700">
                          <span>{rev.user}</span>
                          <span className="text-slate-400 font-semibold">{rev.date}</span>
                        </div>
                        <div className="flex text-yellow-400">
                          {Array.from({ length: rev.rating }).map((_, i) => (
                            <Star key={i} className="h-3 w-3 fill-current" />
                          ))}
                        </div>
                        <p className="text-slate-600 font-semibold text-[11.5px] pt-1">
                          "{rev.comment}"
                        </p>
                      </div>
                    ))
                  )}
                </div>
              </div>

              {/* Submit a review Form */}
              <div className="p-4 bg-slate-50 border rounded-2xl space-y-3">
                <span className="text-[10px] font-black text-slate-700 uppercase tracking-wide block">Write a Product Review</span>
                <form onSubmit={(e) => handleSubmitReview(e, activeAppDetails.id)} className="space-y-3 text-xs">
                  
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-[9px] font-black text-slate-400 uppercase block mb-1">Your Full Name:</label>
                      <input
                        type="text"
                        required
                        placeholder="e.g. Ramesh Reddy"
                        value={reviewName}
                        onChange={(e) => setReviewName(e.target.value)}
                        className="w-full bg-white border font-bold text-slate-700 px-2.5 py-1.5 rounded-lg focus:outline-none"
                      />
                    </div>
                    <div>
                      <label className="text-[9px] font-black text-slate-400 uppercase block mb-1">Star Rating:</label>
                      <select
                        value={reviewRating}
                        onChange={(e) => setReviewRating(Number(e.target.value))}
                        className="w-full bg-white border font-bold text-slate-700 px-2.5 py-1.5 rounded-lg focus:outline-none cursor-pointer"
                      >
                        <option value={5}>5 Stars - Excellent</option>
                        <option value={4}>4 Stars - Good</option>
                        <option value={3}>3 Stars - Average</option>
                        <option value={2}>2 Stars - Poor</option>
                        <option value={1}>1 Star - Very Poor</option>
                      </select>
                    </div>
                  </div>

                  <div>
                    <label className="text-[9px] font-black text-slate-400 uppercase block mb-1">Your Honest Review remarks:</label>
                    <textarea
                      required
                      rows={2}
                      placeholder="Help other farmers by explaining how easy it is to install PX4 telemetry, or how well the micro-irrigation drip schedule syncs..."
                      value={reviewComment}
                      onChange={(e) => setReviewComment(e.target.value)}
                      className="w-full bg-white border font-semibold text-slate-700 px-2.5 py-1.5 rounded-lg focus:outline-none"
                    />
                  </div>

                  <button
                    type="submit"
                    className="px-4 py-1.5 bg-slate-800 hover:bg-slate-750 text-white font-black rounded-lg text-xs cursor-pointer transition-colors"
                  >
                    Post Certified Review
                  </button>

                </form>
              </div>

            </div>

            {/* Footer buttons */}
            <div className="p-4 bg-slate-50 border-t flex justify-end gap-2">
              <button
                onClick={() => setActiveAppDetails(null)}
                className="px-4 py-2 bg-slate-200 hover:bg-slate-250 text-slate-700 text-xs font-black rounded-lg cursor-pointer transition-colors"
              >
                Close Spec Panel
              </button>
            </div>

          </div>

        </div>
      )}

    </div>
  );
}
