// 30 SAMPLE farmer profiles for demos. They are clearly flagged (isSample) in the app.
// Names are placeholders and the numbers are illustrative, NOT real survey data.
// Replace them with your real collected data via Farmer Profiles -> Import CSV.

export interface SampleFarmer { farmerCode: string; farmerName: string; district: string; location: string; crop: string; quantityQuintals: number; expectedPricePerQuintal: number; sellingPreference: string; buyerRequirement: string; verifiedStatus: string; contactPermission: boolean; collectedOn: string }

export const SAMPLE_FARMERS: SampleFarmer[] = [
  { farmerCode: "SAMPLE-001", farmerName: "Sample Farmer 01", district: "Anantapur", location: "Rapthadu", crop: "Groundnut", quantityQuintals: 40, expectedPricePerQuintal: 6800, sellingPreference: "mandi", buyerRequirement: "Needs buyer paying within 3 days", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-15" },
  { farmerCode: "SAMPLE-002", farmerName: "Sample Farmer 02", district: "Anantapur", location: "Kalyandurg", crop: "Groundnut", quantityQuintals: 25, expectedPricePerQuintal: 6700, sellingPreference: "direct_buyer", buyerRequirement: "Oil mill or trader, bulk lot", verifiedStatus: "pending", contactPermission: true, collectedOn: "2026-09-15" },
  { farmerCode: "SAMPLE-003", farmerName: "Sample Farmer 03", district: "Anantapur", location: "Guntakal", crop: "Sunflower", quantityQuintals: 18, expectedPricePerQuintal: 6200, sellingPreference: "fpo", buyerRequirement: "FPO collection centre nearby", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-16" },
  { farmerCode: "SAMPLE-004", farmerName: "Sample Farmer 04", district: "Anantapur", location: "Dharmavaram", crop: "Sweet Orange", quantityQuintals: 30, expectedPricePerQuintal: 3200, sellingPreference: "direct_buyer", buyerRequirement: "Fruit wholesaler, grade A pickup", verifiedStatus: "pending", contactPermission: false, collectedOn: "2026-09-16" },
  { farmerCode: "SAMPLE-005", farmerName: "Sample Farmer 05", district: "Anantapur", location: "Hindupur", crop: "Tomato", quantityQuintals: 22, expectedPricePerQuintal: 1800, sellingPreference: "mandi", buyerRequirement: "Daily mandi sale, transport needed", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-17" },
  { farmerCode: "SAMPLE-006", farmerName: "Sample Farmer 06", district: "Kurnool", location: "Adoni", crop: "Cotton", quantityQuintals: 35, expectedPricePerQuintal: 7400, sellingPreference: "direct_buyer", buyerRequirement: "Ginning mill, moisture below 8%", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-17" },
  { farmerCode: "SAMPLE-007", farmerName: "Sample Farmer 07", district: "Kurnool", location: "Nandyal", crop: "Bengalgram", quantityQuintals: 28, expectedPricePerQuintal: 5600, sellingPreference: "mandi", buyerRequirement: "Cash payment preferred", verifiedStatus: "pending", contactPermission: true, collectedOn: "2026-09-18" },
  { farmerCode: "SAMPLE-008", farmerName: "Sample Farmer 08", district: "Kurnool", location: "Yemmiganur", crop: "Onion", quantityQuintals: 50, expectedPricePerQuintal: 1500, sellingPreference: "mandi", buyerRequirement: "Cold storage space for 2 weeks", verifiedStatus: "pending", contactPermission: false, collectedOn: "2026-09-18" },
  { farmerCode: "SAMPLE-009", farmerName: "Sample Farmer 09", district: "Kurnool", location: "Pattikonda", crop: "Groundnut", quantityQuintals: 20, expectedPricePerQuintal: 6600, sellingPreference: "fpo", buyerRequirement: "Joint sale through FPO", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-19" },
  { farmerCode: "SAMPLE-010", farmerName: "Sample Farmer 10", district: "Chittoor", location: "Madanapalle", crop: "Tomato", quantityQuintals: 45, expectedPricePerQuintal: 1900, sellingPreference: "direct_buyer", buyerRequirement: "Retail chain, crates supplied", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-19" },
  { farmerCode: "SAMPLE-011", farmerName: "Sample Farmer 11", district: "Chittoor", location: "Punganur", crop: "Mango", quantityQuintals: 60, expectedPricePerQuintal: 4200, sellingPreference: "direct_buyer", buyerRequirement: "Pulp factory, season contract", verifiedStatus: "pending", contactPermission: true, collectedOn: "2026-09-20" },
  { farmerCode: "SAMPLE-012", farmerName: "Sample Farmer 12", district: "Chittoor", location: "Palamaner", crop: "Banana", quantityQuintals: 70, expectedPricePerQuintal: 1600, sellingPreference: "mandi", buyerRequirement: "Truck pickup from farm", verifiedStatus: "pending", contactPermission: false, collectedOn: "2026-09-20" },
  { farmerCode: "SAMPLE-013", farmerName: "Sample Farmer 13", district: "Guntur", location: "Tenali", crop: "Chilli", quantityQuintals: 15, expectedPricePerQuintal: 14500, sellingPreference: "direct_buyer", buyerRequirement: "Exporter, dried, low moisture", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-21" },
  { farmerCode: "SAMPLE-014", farmerName: "Sample Farmer 14", district: "Guntur", location: "Sattenapalli", crop: "Cotton", quantityQuintals: 40, expectedPricePerQuintal: 7300, sellingPreference: "mandi", buyerRequirement: "Cotton Corporation procurement", verifiedStatus: "pending", contactPermission: true, collectedOn: "2026-09-21" },
  { farmerCode: "SAMPLE-015", farmerName: "Sample Farmer 15", district: "Guntur", location: "Narasaraopet", crop: "Turmeric", quantityQuintals: 12, expectedPricePerQuintal: 12800, sellingPreference: "fpo", buyerRequirement: "Processing unit tie-up", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-22" },
  { farmerCode: "SAMPLE-016", farmerName: "Sample Farmer 16", district: "Krishna", location: "Gudivada", crop: "Paddy", quantityQuintals: 120, expectedPricePerQuintal: 2300, sellingPreference: "mandi", buyerRequirement: "Procurement centre within 10 km", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-22" },
  { farmerCode: "SAMPLE-017", farmerName: "Sample Farmer 17", district: "Krishna", location: "Machilipatnam", crop: "Paddy", quantityQuintals: 90, expectedPricePerQuintal: 2250, sellingPreference: "mandi", buyerRequirement: "Rice miller, 15 day payment ok", verifiedStatus: "pending", contactPermission: false, collectedOn: "2026-09-23" },
  { farmerCode: "SAMPLE-018", farmerName: "Sample Farmer 18", district: "Krishna", location: "Nuzvid", crop: "Mango", quantityQuintals: 55, expectedPricePerQuintal: 4500, sellingPreference: "direct_buyer", buyerRequirement: "Exporter, grade A only", verifiedStatus: "pending", contactPermission: true, collectedOn: "2026-09-23" },
  { farmerCode: "SAMPLE-019", farmerName: "Sample Farmer 19", district: "West Godavari", location: "Tadepalligudem", crop: "Paddy", quantityQuintals: 140, expectedPricePerQuintal: 2300, sellingPreference: "mandi", buyerRequirement: "Government procurement", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-24" },
  { farmerCode: "SAMPLE-020", farmerName: "Sample Farmer 20", district: "West Godavari", location: "Eluru", crop: "Maize", quantityQuintals: 65, expectedPricePerQuintal: 2100, sellingPreference: "direct_buyer", buyerRequirement: "Poultry feed unit", verifiedStatus: "pending", contactPermission: true, collectedOn: "2026-09-24" },
  { farmerCode: "SAMPLE-021", farmerName: "Sample Farmer 21", district: "East Godavari", location: "Rajahmundry", crop: "Banana", quantityQuintals: 80, expectedPricePerQuintal: 1700, sellingPreference: "direct_buyer", buyerRequirement: "Wholesaler, weekly lifting", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-25" },
  { farmerCode: "SAMPLE-022", farmerName: "Sample Farmer 22", district: "East Godavari", location: "Amalapuram", crop: "Coconut", quantityQuintals: 30, expectedPricePerQuintal: 2800, sellingPreference: "fpo", buyerRequirement: "Copra unit collection", verifiedStatus: "pending", contactPermission: false, collectedOn: "2026-09-25" },
  { farmerCode: "SAMPLE-023", farmerName: "Sample Farmer 23", district: "Prakasam", location: "Markapur", crop: "Chilli", quantityQuintals: 14, expectedPricePerQuintal: 14200, sellingPreference: "direct_buyer", buyerRequirement: "Cold storage + exporter", verifiedStatus: "pending", contactPermission: true, collectedOn: "2026-09-26" },
  { farmerCode: "SAMPLE-024", farmerName: "Sample Farmer 24", district: "Prakasam", location: "Ongole", crop: "Tobacco", quantityQuintals: 25, expectedPricePerQuintal: 9800, sellingPreference: "undecided", buyerRequirement: "Not decided yet", verifiedStatus: "pending", contactPermission: false, collectedOn: "2026-09-26" },
  { farmerCode: "SAMPLE-025", farmerName: "Sample Farmer 25", district: "Nellore", location: "Kavali", crop: "Paddy", quantityQuintals: 100, expectedPricePerQuintal: 2280, sellingPreference: "mandi", buyerRequirement: "Rice miller nearby", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-27" },
  { farmerCode: "SAMPLE-026", farmerName: "Sample Farmer 26", district: "Kadapa", location: "Pulivendula", crop: "Banana", quantityQuintals: 75, expectedPricePerQuintal: 1650, sellingPreference: "direct_buyer", buyerRequirement: "Fruit wholesaler, sorted bunches", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-27" },
  { farmerCode: "SAMPLE-027", farmerName: "Sample Farmer 27", district: "Kadapa", location: "Proddatur", crop: "Turmeric", quantityQuintals: 10, expectedPricePerQuintal: 12600, sellingPreference: "fpo", buyerRequirement: "Spice board registered buyer", verifiedStatus: "pending", contactPermission: true, collectedOn: "2026-09-28" },
  { farmerCode: "SAMPLE-028", farmerName: "Sample Farmer 28", district: "Srikakulam", location: "Palasa", crop: "Cashew", quantityQuintals: 8, expectedPricePerQuintal: 11000, sellingPreference: "fpo", buyerRequirement: "Processing unit, raw nuts", verifiedStatus: "pending", contactPermission: false, collectedOn: "2026-09-29" },
  { farmerCode: "SAMPLE-029", farmerName: "Sample Farmer 29", district: "Visakhapatnam", location: "Anakapalle", crop: "Sugarcane", quantityQuintals: 200, expectedPricePerQuintal: 350, sellingPreference: "contract", buyerRequirement: "Sugar factory contract", verifiedStatus: "verified", contactPermission: true, collectedOn: "2026-09-30" },
  { farmerCode: "SAMPLE-030", farmerName: "Sample Farmer 30", district: "Vizianagaram", location: "Bobbili", crop: "Redgram (Tur)", quantityQuintals: 16, expectedPricePerQuintal: 7200, sellingPreference: "mandi", buyerRequirement: "Dal mill, 15 day payment ok", verifiedStatus: "pending", contactPermission: true, collectedOn: "2026-10-01" },
];
