// ==========================================
// POSTGRES SCHEMA - core marketplace loop
// ==========================================
// farmer -> farm -> crop -> listing -> bid -> order -> payment (escrow) -> shipment
//
// Conventions
//  - Money is stored as integer PAISE (BIGINT), never floats. 1 rupee = 100 paise.
//  - Quantities are kilograms (NUMERIC).
//  - IDs are UUIDs generated by the app.
//  - user ids (owner_id, seller_id, buyer_id ...) are the ids from the `users`
//    table in SQLite (server/db.ts). They are stored as TEXT without a foreign
//    key because accounts still live in SQLite. Moving `users` into Postgres is
//    the natural next step; then these become real FOREIGN KEYs.
//  - Every statement is idempotent (IF NOT EXISTS) so it is safe to run on every
//    startup. For schema CHANGES later, switch to a real migration tool.
//
// Statements are separated by a line containing only ";;" so they can be run
// one at a time (works on real Postgres and on the in-memory pg-mem used in dev).

export const SCHEMA_STATEMENTS: string[] = `
CREATE TABLE IF NOT EXISTS farms (
  id          UUID PRIMARY KEY,
  owner_id    TEXT NOT NULL,
  name        TEXT NOT NULL,
  village     TEXT,
  district    TEXT NOT NULL,
  state       TEXT NOT NULL,
  area_acres  NUMERIC NOT NULL CHECK (area_acres > 0),
  soil_type   TEXT,
  latitude    NUMERIC,
  longitude   NUMERIC,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
)
;;
CREATE INDEX IF NOT EXISTS idx_farms_owner ON farms(owner_id)
;;
CREATE TABLE IF NOT EXISTS crops (
  id                    UUID PRIMARY KEY,
  farm_id               UUID NOT NULL REFERENCES farms(id) ON DELETE CASCADE,
  crop_name             TEXT NOT NULL,
  variety               TEXT,
  area_acres            NUMERIC NOT NULL CHECK (area_acres > 0),
  sown_on               DATE,
  expected_harvest_on   DATE,
  status                TEXT NOT NULL DEFAULT 'growing' CHECK (status IN ('planned','growing','harvested')),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
)
;;
CREATE INDEX IF NOT EXISTS idx_crops_farm ON crops(farm_id)
;;
CREATE TABLE IF NOT EXISTS listings (
  id                        UUID PRIMARY KEY,
  seller_id                 TEXT NOT NULL,
  farm_id                   UUID REFERENCES farms(id) ON DELETE SET NULL,
  crop_id                   UUID REFERENCES crops(id) ON DELETE SET NULL,
  crop_name                 TEXT NOT NULL,
  variety                   TEXT,
  grade                     TEXT,
  district                  TEXT,
  state                     TEXT,
  quantity_kg               NUMERIC NOT NULL CHECK (quantity_kg > 0),
  available_kg              NUMERIC NOT NULL CHECK (available_kg >= 0),
  min_price_paise_per_kg    BIGINT NOT NULL CHECK (min_price_paise_per_kg >= 0),
  status                    TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','sold_out','closed')),
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (available_kg <= quantity_kg)
)
;;
CREATE INDEX IF NOT EXISTS idx_listings_status_crop ON listings(status, crop_name)
;;
CREATE INDEX IF NOT EXISTS idx_listings_seller ON listings(seller_id)
;;
CREATE TABLE IF NOT EXISTS bids (
  id                  UUID PRIMARY KEY,
  listing_id          UUID NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  buyer_id            TEXT NOT NULL,
  quantity_kg         NUMERIC NOT NULL CHECK (quantity_kg > 0),
  price_paise_per_kg  BIGINT NOT NULL CHECK (price_paise_per_kg > 0),
  status              TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','withdrawn')),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  decided_at          TIMESTAMPTZ
)
;;
CREATE INDEX IF NOT EXISTS idx_bids_listing ON bids(listing_id)
;;
CREATE INDEX IF NOT EXISTS idx_bids_buyer ON bids(buyer_id)
;;
CREATE TABLE IF NOT EXISTS orders (
  id                  UUID PRIMARY KEY,
  listing_id          UUID NOT NULL REFERENCES listings(id),
  bid_id              UUID UNIQUE REFERENCES bids(id),
  seller_id           TEXT NOT NULL,
  buyer_id            TEXT NOT NULL,
  crop_name           TEXT NOT NULL,
  quantity_kg         NUMERIC NOT NULL CHECK (quantity_kg > 0),
  price_paise_per_kg  BIGINT NOT NULL CHECK (price_paise_per_kg > 0),
  total_paise         BIGINT NOT NULL CHECK (total_paise > 0),
  status              TEXT NOT NULL DEFAULT 'pending_payment'
                      CHECK (status IN ('pending_payment','paid','shipped','delivered','completed','cancelled')),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
)
;;
CREATE INDEX IF NOT EXISTS idx_orders_buyer ON orders(buyer_id)
;;
CREATE INDEX IF NOT EXISTS idx_orders_seller ON orders(seller_id)
;;
CREATE TABLE IF NOT EXISTS payments (
  id             UUID PRIMARY KEY,
  order_id       UUID NOT NULL REFERENCES orders(id),
  amount_paise   BIGINT NOT NULL CHECK (amount_paise > 0),
  provider       TEXT NOT NULL,
  provider_ref   TEXT,
  status         TEXT NOT NULL DEFAULT 'captured' CHECK (status IN ('created','captured','failed','refunded')),
  escrow_status  TEXT NOT NULL DEFAULT 'held' CHECK (escrow_status IN ('held','released','refunded')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  released_at    TIMESTAMPTZ
)
;;
CREATE INDEX IF NOT EXISTS idx_payments_order ON payments(order_id)
;;
CREATE TABLE IF NOT EXISTS shipments (
  id             UUID PRIMARY KEY,
  order_id       UUID NOT NULL UNIQUE REFERENCES orders(id),
  carrier_id     TEXT,
  tracking_code  TEXT NOT NULL,
  pickup_address TEXT,
  drop_address   TEXT,
  status         TEXT NOT NULL DEFAULT 'booked' CHECK (status IN ('booked','picked_up','in_transit','delivered')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
)
;;
CREATE TABLE IF NOT EXISTS shipment_events (
  id           UUID PRIMARY KEY,
  shipment_id  UUID NOT NULL REFERENCES shipments(id) ON DELETE CASCADE,
  status       TEXT NOT NULL,
  note         TEXT,
  actor_id     TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
)
;;
CREATE INDEX IF NOT EXISTS idx_shipment_events_shipment ON shipment_events(shipment_id)
;;
CREATE TABLE IF NOT EXISTS warehouse_stock (
  id             UUID PRIMARY KEY,
  owner_id       TEXT NOT NULL,
  warehouse_name TEXT NOT NULL,
  location       TEXT,
  crop_name      TEXT NOT NULL,
  quantity_kg    NUMERIC NOT NULL CHECK (quantity_kg >= 0),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
)
;;
CREATE INDEX IF NOT EXISTS idx_stock_owner ON warehouse_stock(owner_id)
`
  .split(/^;;$/m)
  .map((s) => s.trim())
  .filter(Boolean);
